[project]
name = "MLSensorFaultDetection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "requests", "pandas", "numpy", "pymongo",]

[tool.setuptools.packages.find]
include = [ "sensor*", "utils*",]
exclude = [ "Tests*",]
